project_id = "gnkuikentdtnatazeriu"

[functions.load-session-responses]
verify_jwt = false

[functions.start_assessment]
verify_jwt = false

[functions.finalizeAssessment]
verify_jwt = false

[functions.score_prism]
verify_jwt = false

[functions.score_fc_session]
verify_jwt = false

[functions.get-results-by-session]
verify_jwt = false

[functions.delete-session]
verify_jwt = false

[functions.get_progress]
verify_jwt = false

[functions.getConfig]
verify_jwt = false

[functions.getView]
verify_jwt = false

[functions.find-session-by-email]
verify_jwt = false

[functions.analytics-get]
verify_jwt = false

[functions.compute-psychometrics]
verify_jwt = false

[auth]
# (manage OTP expiry & password policies in the Supabase Dashboard)
