project_id = "gnkuikentdtnatazeriu"

[functions.getResultsBySession]
verify_jwt = false

[functions.finalizeAssessment]
verify_jwt = false

[functions.score_prism]
verify_jwt = false

[functions.compare_runs]
verify_jwt = true

[functions.cleanup_profiles]
verify_jwt = false

[functions.backfill_profiles]
verify_jwt = false

[functions.chatgpt-gateway]
verify_jwt = false

[functions.updateSystemStatus]
verify_jwt = false

[functions.getConfig]
verify_jwt = false

[functions.getView]
verify_jwt = false

[functions.import_questions]
verify_jwt = false

[functions.save_response]
verify_jwt = false

[functions.get_progress]
verify_jwt = false

[functions.score_fc_session]
verify_jwt = false

[functions.get-results-by-session]
verify_jwt = false

[functions.notify_admin]
verify_jwt = false

[auth]
# (manage OTP expiry & password policies in the Supabase Dashboard)