project_id = "gnkuikentdtnatazeriu"

[functions.score_prism]
verify_jwt = false

[functions.compare_runs]
verify_jwt = true

[functions.cleanup_profiles]
verify_jwt = false

[functions.backfill_profiles]
verify_jwt = false

[functions.chatgpt-gateway]
verify_jwt = false

[functions.finalizeAssessment]
verify_jwt = false

[functions.updateSystemStatus]
verify_jwt = false

[functions.getConfig]
verify_jwt = false

[functions.getView]
verify_jwt = false

[functions.import_questions]
verify_jwt = false

[functions.save_response]
verify_jwt = false
