project_id = "gnkuikentdtnatazeriu"

[functions.score_prism]
verify_jwt = false

[functions.compare_runs]
verify_jwt = true

[functions.cleanup_profiles]
verify_jwt = false

[functions.backfill_profiles]
verify_jwt = false
