project_id = "gnkuikentdtnatazeriu"

[functions.submit-contact-form]
verify_jwt = false

[functions.refresh-analytics]
verify_jwt = false

[functions.load-session-responses]
verify_jwt = false

[functions.start_assessment]
verify_jwt = false

[functions.finalizeAssessment]
verify_jwt = false

[functions.score_prism]
verify_jwt = false

[functions.score_fc_session]
verify_jwt = false

[functions.get-results-by-session]
verify_jwt = false

[functions.delete-session]
verify_jwt = false

[functions.get_progress]
verify_jwt = false

[functions.getConfig]
verify_jwt = false

[functions.getView]
verify_jwt = false

[functions.find-session-by-email]
verify_jwt = false

[functions.analytics-get]
verify_jwt = false

[functions.analytics-export]
verify_jwt = false

[functions.compute-reliability]
verify_jwt = false

[functions.compute-retest]
verify_jwt = false

[functions.link_session_to_account]
verify_jwt = false

[functions.get-or-create-share-token]
verify_jwt = false

[functions.admin-run-reliability]
verify_jwt = false

[functions.admin-run-retest]
verify_jwt = false

[functions.admin-calibration]
verify_jwt = false

[functions.admin-get-metrics]
verify_jwt = false

[functions.cfa-ingest]
verify_jwt = false

[functions.admin-backfill-profiles]
verify_jwt = false

[functions.admin-backfill-scoring_results]
verify_jwt = false

[functions.cleanup-sessions]
verify_jwt = false

[functions.cron-force-finalize-248]
verify_jwt = false

[functions.health-check-scoring]
verify_jwt = false

[functions.post-survey-questions]
verify_jwt = false

[functions.post-survey-submit]
verify_jwt = false

[functions.send-completion-email]
verify_jwt = false

[functions.send-feedback-reminders]
verify_jwt = false

[functions.stripe-portal]
verify_jwt = true

[functions.checkout-membership]
verify_jwt = true

[functions.checkout-advanced]
verify_jwt = true

[auth]
# (manage OTP expiry & password policies in the Supabase Dashboard)
