project_id = "gnkuikentdtnatazeriu"

[functions.admin-batch-recompute]
verify_jwt = false

[functions.finalizeAssessment]
verify_jwt = false

[functions.score_prism]
verify_jwt = false

[functions.score_fc_session]
verify_jwt = false

[functions.get-results-by-session]
verify_jwt = false

[functions.migrate-all-scoring]
verify_jwt = false

[functions.recompute-new-metrics]
verify_jwt = false

[functions.cleanup-duplicate-sessions]
verify_jwt = false

[functions.delete-session]
verify_jwt = false

[functions.save_response]
verify_jwt = false

[functions.get_progress]
verify_jwt = false

[functions.getConfig]
verify_jwt = false

[functions.getView]
verify_jwt = false

[auth]
# (manage OTP expiry & password policies in the Supabase Dashboard)
