-- Update refresh_psych_kpis to include STATE overlay MVs
CREATE OR REPLACE FUNCTION public.refresh_psych_kpis()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- STATE overlay MVs (new)
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_state_overlay_daily; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_state_overlay; EXCEPTION WHEN OTHERS THEN NULL; END;
  
  -- Core psychometric MVs (order matters - dependencies)
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_scale_corr; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_internal; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_external; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_ave_cr; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_stability; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_invariance; EXCEPTION WHEN OTHERS THEN NULL; END;
  
  -- KPI displays (depend on core MVs above)
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_neuroticism; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_scale_norms; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_release_gates; EXCEPTION WHEN OTHERS THEN NULL; END;
  
  -- Other existing MVs
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_engagement; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_construct_coverage; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_reliability; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_retest; EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN REFRESH MATERIALIZED VIEW CONCURRENTLY mv_kpi_post_survey; EXCEPTION WHEN OTHERS THEN NULL; END;
END;
$$;