// This file is automatically generated. Do not edit it directly.
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using singleton client to avoid Multiple GoTrueClient instances
export { supabase } from '@/lib/supabaseClient';