name: verify-smoke

on:
  push:
  pull_request:

jobs:
  verify-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm run check:no-legacy
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run verify:functions
      - run: npx tsx --test --test-reporter=junit tests/fetchResults.test.ts tests/results.integration.test.ts > junit.xml
      - name: smoke
        run: npm run verify:smoke > smoke-report.json
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SMOKE_SESSION_ID: ${{ secrets.SMOKE_SESSION_ID }}
          SMOKE_SHARE_TOKEN: ${{ secrets.SMOKE_SHARE_TOKEN }}
        continue-on-error: ${{ github.event_name == 'pull_request' }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit
          path: junit.xml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-report
          path: smoke-report.json
